log-viewer:
  port: 8887
  sources:
    ftp:
      ftpserver1:
        host: 152.151.150.100
        port: 21
        user: ftpuser
        password: IlOveSeCreTs
      ftpserver2:
        ip: xxx.xxx.xxx.xxx
        port: xx
        user: xxxxx
        password: xxxxx
