log-viewer:
  port: 8887
  sources:
    ftp:
      ftpserver1:
        host: 152.151.150.100
        port: 21
        user: ftpuser
        password: IlOveSeCreTs
        secure: true
        logs:
          - aninteresting.log
          - another.log
      ftpserver2:
        host: xxx.xxx.xxx.xxx
        port: xx
        user: xxxxx
        password: xxxxx
        secure: true
        logs:
          - ....log
          - ....log
  download:
    folder: /path/to/download/folder
