log-viewer:
  port: 8887
  auth:
    key: <<set a secret key here>>
  users:
    - username: charles
      password: 1ebc88f7f9e2f673bd331773af5d1df2
    - username: another-fellow
      password: cc03e747a6afbbcbf8be7668acfebee5
    - username: ...
      password: <<md5 of user+password>>
  transformers:
    java-transformers:
      - match: com.r2.util.SQSUtil
        find: /(Payload:.*), (messageId:.*)/
        replace: $2,$1
      - find: /at (com\.jashmore\..*\n|java\..*\n|com\.mashape\..*\n|org\.json\..*\n|org\.jasypt\..*\n)/g
        replace: "..."
    python-transformers:
      - find: /\u001b\[[^m]*m/g
        replace: ""
    cpp-transformers:
      - match: /error-code:9[0-9][0-9]/
        find: /error_detail: (.*\)/
        replace: ""

  sources:
    file:
      downloads:
        transformers: java-transformers
        folder: /Users/charleslobo/Downloads
        logs:
          - mylog1.log
          - yourlog2.log
    ftp:
      ftpserver1:
        host: 152.151.150.100
        port: 21
        user: ftpuser
        password: IlOveSeCreTs
        secure: true
        transformers: cpp-transformers
        logs:
          - aninteresting.log
          - another.log
      ftpserver2:
        host: xxx.xxx.xxx.xxx
        port: xx
        user: xxxxx
        password: xxxxx
        secure: true
        logs:
          - ....log
          - ....log
  download:
    folder: /path/to/download/folder
